__author__ = "Abdulrahman Alfawal"
__email__ = "projects@alfawal.dev"
__app_name__ = "LoA: League of Archives"
__app_description__ = f"{__app_name__} - Scrape, export, visualize and stream data from OP.GG and Blitz.GG"
__license__ = "MIT"
__repo_url__ = "https://github.com/alfawal/LoA"
__version__ = "0.1.0"
